# Generated by Django 4.2.29 on 2026-03-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nechilibi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
