# Generated by Django 4.2.29 on 2026-03-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nechilibi', '0002_delete_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('holiday', 'School Holiday'), ('exam', 'Examinations'), ('event', 'School Event'), ('other', 'Other')], default='event', max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, help_text='Leave blank for single-day entry', null=True)),
                ('academic_year', models.CharField(help_text='e.g. 2026', max_length=9)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['date_from'],
            },
        ),
        migrations.CreateModel(
            name='TermDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. 2026', max_length=9)),
                ('term', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='Mark the running term')),
                ('notes', models.TextField(blank=True, help_text='Optional note e.g. "Includes Prize Giving Day"')),
            ],
            options={
                'verbose_name': 'Term Date',
                'verbose_name_plural': 'Term Dates',
                'ordering': ['academic_year', 'term'],
                'unique_together': {('academic_year', 'term')},
            },
        ),
    ]
