# Generated by Django 4.2.29 on 2026-03-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nechilibi', '0004_add_zimsec_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. 2026', max_length=4, unique=True)),
                ('currency', models.CharField(choices=[('USD', 'USD ($)'), ('ZIG', 'ZiG'), ('ZWL', 'ZWL')], default='USD', max_length=5)),
                ('is_published', models.BooleanField(default=True)),
                ('effective_from', models.DateField(help_text='Date fees come into effect')),
                ('notes', models.TextField(blank=True, help_text='General notes shown at the bottom of the page')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['-academic_year'],
            },
        ),
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_group', models.CharField(choices=[('form1_2', 'Form 1 & 2'), ('form3_4', 'Form 3 & 4'), ('form5_6', 'Form 5 & 6 (A-Level)'), ('all', 'All Forms')], max_length=20)),
                ('category', models.CharField(choices=[('tuition', 'Tuition Fees'), ('boarding', 'Boarding Fees'), ('development', 'Development Levy'), ('zimsec', 'ZIMSEC / Exam Fees'), ('sports', 'Sports Levy'), ('library', 'Library & Resources'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('per_term', 'Per Term'), ('once_off', 'Once Off (Annual)')], default='per_term', max_length=20)),
                ('notes', models.CharField(blank=True, help_text='Small note e.g. "Form 4 only"', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nechilibi.feestructure')),
            ],
            options={
                'verbose_name': 'Fee Item',
                'verbose_name_plural': 'Fee Items',
                'ordering': ['form_group', 'order', 'category'],
            },
        ),
    ]
