# Generated by Django 4.2.29 on 2026-03-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_videogallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogallery',
            name='youtube_url',
            field=models.URLField(help_text='YouTube video URL (e.g. https://www.youtube.com/watch?v=XXXX)'),
        ),
    ]
