# Generated by Django 4.2.29 on 2026-03-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_nullable_category_and_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
