# Generated by Django 4.2.29 on 2026-03-27 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_subject_subject_template'),
        ('institute', '0017_schoolsettings'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='educationboard',
            name='institute_educationboard_country_name_uniq',
        ),
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(help_text='Province/district code', max_length=10),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='current_session',
            field=models.ForeignKey(blank=True, help_text='Current active academic session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutes_using_as_current', to='academics.academicsession'),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='institute_type',
            field=models.CharField(blank=True, choices=[('school', 'High School')], default='school', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='educationboard',
            unique_together={('country', 'name')},
        ),
    ]
