# Generated by Django 4.2.29 on 2026-03-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_subject_subject_template'),
        ('teachers', '0006_teacher_institute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['role', 'title']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['designation__role', 'name']},
        ),
        migrations.AddField(
            model_name='designation',
            name='role',
            field=models.CharField(choices=[('headmaster', 'Headmaster'), ('deputy', 'Deputy Headmaster'), ('senior_teacher', 'Senior Teacher'), ('teacher', 'Teacher'), ('other', 'Other')], default='teacher', help_text='Controls display prominence on the website.', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography shown on the website.', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this teacher from the website.'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects this teacher teaches.', related_name='assigned_teachers', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code e.g. +2637...', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers'),
        ),
    ]
