# Generated by Django 4.2.29 on 2026-03-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_add_role_social_subjects_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['role', 'name']},
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('headmaster', 'Headmaster'), ('deputy', 'Deputy Headmaster'), ('senior_teacher', 'Senior Teacher'), ('teacher', 'Ordinary Teacher')], default='teacher', help_text="Select the teacher's position at the school.", max_length=20, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.ForeignKey(help_text='Job title/department label (e.g. "Head of Science")', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='teachers.designation'),
        ),
    ]
